##
# Testes para intake.py
#
# Todos os testes no folder "test" são executados quando a ação "Test" é invocada.
#
##


import unittest
from "path para" intake.py import ler_seq, ler_FASTA_seq
class MyTestCase(unittest.TestCase):
    def test_ler_seq(self):
        
        self.assertEqual(ler_seq(file), RESULTADO_ESPERADO)
        self.assertEqual(True, False)


    def test_ler_FASTA_seq(self):
        
        file = open(path é ??, mode='r', encoding='utf-8') # meter o path
        self.assertEqual(ler_FASTA_seq(file),"MSSAFVSVRNFLQRVVLGVDTKKNIYDDEINSLDTEQINDGAPVEKKSPLGYNVSDFTACYLIIEGVIGTGIFATPATILKSVGSVGASYVFWCVGFVVNQFTVLMYVEYVTYFRRRSGAQVAYLEQAYPKPKFLVPVLYAAVSVTLSYITSSAASFSQYVFEGANYEATAWQQRGLSILPLFLAAIFTTLSTKWTLRLNSIIGWCKVCFIFFIAFSGFAALAGSTKAPKNHDIFKNAWEGTTTDGNSISNAILKVVFSFGGAPYAFTVVAETHPKNTIKTYKYFVPFTMFLIFIMYILCVTAYYAGIDSKAEITNSGNVVAAVYFRKIFETEAAVRAMCAFVALSSFGHMMTAFIAHSRILRECGRQGVLPYSRLWTSVKPFGTPLLPIIVTLCVNLIVLLAPPPGDAYNFIVDLGTYADGIFTVLLSVGLFRIRRQRKKKGLGYREFHLPTVLLVIVLLWALFVLAMSFVPPKGTLIGSDVSFFYATYPITTFGIFGLCILYYIVWALVLPKFGKFERRVTSYELPNGERGQTLIKVPLGEIESWDKEHNSQKQSLFASNFEDEPERSLELNITEVNSKKEATS")
        self.assertEqual(ler_FASTA_seq(file),"MSFNVDEKIPSFDGKLLKLSHNSTITHTKMLLSLYLPHQYFEKADNKVLPVILFLSGLNCSPDNPTEKSFIQPYANMYGFSVLFPDTSPRINDVRLKKGIGSSFYLDATENPWCKNFKMYSYIMKDLISNIGKEFPKLDTDNMSICGHSMGGFGALMFYLKTPEMFKSCSAFAPLTHPSICPGENKFFKLFLGSAQSEWKKYDPCELIKTYNGPKRPILIHQGTGDKYYIGKELLPEDFVKASEGTILEGLINIKFKDGYGHNYYLVSSFMAEQCLFHAKYLGLI")
        self.assertEqual(ler_FASTA_seq(file),"MSILSSLKEFWNSLKTADPLTLRTEYIDIDVKRERKPIRKTTKFQKHHFFTVFNFYPSNYSTAEKKLLLKFDISVFLFMCASTFTKNLDNANISTAYVSGMKEDIHVVGNELNIFSTMYTVGYALFQIPLTLLITKPQLSRYLLIICEFAWGILTLGNAFVKTPQQVYAIRFLIGVTEACSYPASYVIFSSYLTDQELFTRAGFYGAFGTAGSAVSGSLQTRMRDSLEGVCGLAGWRWQFIMDFVLTMGVTVYGFFLFPGIPTSCRKFGLFTEDDMIFARKRVEKKIAIPRKFDRKALKETFGTWQLYAFTILQTLHHSCYYFNGGKLYMASRKDLYTTDDVTNWHTYMSLIGIPCAIFISPLVEWLGKLPVVFVIYIIGYYAAIVTVVWNVKESVLLSSFFLIHVVRDGLSQVYYAWAASLCRDDVEKKALVLSIMQAICYATNSWVTPLQYNTKWSPRFKVGYIANLVIVICTSIWFVVTWILDHYDLQLIPKYAGHRHLDKEGNMQASESQLLNDNIINIGNENVQRTDSSCSLIQSVTYLSSTKEKK")
        self.assertEqual(ler_FASTA_seq(file),"MNFNIFEQKESFGGKLLKLTHNSSVTHTTMTLNLYLPHQYFDCHTAESLPIILFLAGFGCNPNNPSEKSFIQPYANEYGFAVLMPDTSPRVKDGQYKLGDGANFYLDATQKPWDKMFNMYSYIIKDLIPNIGKSFKILDLKRMSICGHSMGGLGSLLLFLKNPNLFKCCSAFAPLTHPMVCPGENKYFKIYLGSDKLEWAKYDPCELIKAYVGPKRPILIFQGTNDKFYIGKELLPEQFLKSSKGTLLEGLVDLRLEKGYDHSYYFVSSFMSETCAFHAKYLGLA")
        
        file.close
if __name__ == '__main__':
    unittest.main()

